---
- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - hera_home is defined
      - workdir is defined
    quiet: true
    fail_msg: "Missing required parameters"

- name: "Check that workdir and HERA_HOME exists."
  ansible.builtin.include_role:
    name: eris_hera_commons
    tasks_from: check_dir.yml
  vars:
    variable_name: "{{ item.variable_name }}"
    directory_path: "{{ item.directory_path }}"
  loop:
    - { variable_name: 'HERA_HOME', directory_path: "{{ hera_home }}" }
    - { variable_name: 'workdir', directory_path: "{{ workdir }}" }

- block:
    - name: "HERA: stop"
      ansible.builtin.command: >
        bash -x {{ hera_home }}/hera.sh stop
      args:
        chdir: "{{ workdir }}"
      no_log: False
      register: hera_stop
      environment:
        JOB_NAME: "{{ job_name }}"
        HERA_DEBUG: true
        HERA_HOSTNAME: "olympus"
  rescue:
    - name: "HERA: stop failed."
      ansible.builtin.debug:
        msg: "No container to destroy."

- name: "Display result of HERA stop operation"
  ansible.builtin.debug:
    msg: "{{ hera_stop }}"
  when:
    - hera_debug

# Mandatory configuration for Molecule to function.
- name: Populate instance config
  ansible.builtin.set_fact:
    instance_conf: {}

- name: Dump instance config
  ansible.builtin.copy:
    content: |
      # Molecule managed

      {{ instance_conf | to_json | from_json | to_yaml }}
    dest: "{{ molecule_instance_config }}"
    mode: '0644'
  when: server.changed | default(false) | bool
