---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  vars:
    hera_home: "{{ lookup('env', 'HERA_HOME') }}"
    hera_debug: "{{ lookup('env', 'HERA_DEBUG') | default(False) }}"
    hera_hostname: "{{ lookup('env', 'HERA_HOSTNAME') | default('olympus') }}"
    workdir: "{{ lookup('env', 'WORKDIR') }}"
    job_name: "{{ lookup('env', 'JOB_NAME') | default('ansible') }}-slave"
  tasks:

    - debug:
        msg: "Running on {{ ansible_nodename }} using {{ ansible_version.full }}."

    - assert:
        that:
          - hera_home is defined
          - workdir is defined
        quiet: true

    - stat:
        path: "{{ workdir }}"
      register: is_workdir

    - assert:
        that:
          - is_workdir is defined
          - is_workdir.stat is defined
          - is_workdir.stat.exists is defined
          - is_workdir.stat.exists
        quiet: true
        fail_msg: "Provided 'workdir' does not exist: {{ workdir }}"

    - block:
        - command: >
            bash -x {{ hera_home }}/hera.sh stop
          args:
            chdir: "{{ workdir }}"
          no_log: False
          register: hera_stop
          environment:
            JOB_NAME: "{{ job_name }}"
            HERA_DEBUG: "{{ hera_debug }}"
            HERA_HOSTNAME: "{{ hera_hostname }}"
      rescue:
        - debug:
            msg: "No container to destroy."

    - debug:
        msg: "{{ hera_stop }}"
      when:
        - hera_debug

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
      when: server.changed | default(false) | bool
